### ISSUE TITLE
convert drawing points into google training format

### ISSUE THREAD

**Issue by julien-ur** [julien-ur/ITT-Abschlussprojekt#8]

**Comment by tran-tuananh** [comment]
Drawing Points currently converted to rgba pixel array by @TobiasZ-UR.
To do: scale to 28x28 pixel array, make grayscale

**Comment by tran-tuananh** [comment]
Implementation in 196de0cfe92fff5954c28060ce7b8eb4e4f4643e, further testing necessary

**Comment by tran-tuananh** [comment]
Implementation fixed in b93023d7bf3566d7b3aebee046953d6771ac1fb8
